name: aaftf-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - samtools>=1.24,<2
  - biopython
  - bwa
  - minimap2
  - freebayes
  - yak
  - polypolish
  - nextpolish2
  - blast
  - diamond
  - sourmash
  - bowtie2
  - trimmomatic
  - spades
  - fastp
  - flye
  - racon
  - fastqc
  - hifiasm
  - kraken2
  - gfatools
  - novoplasty
  - ncbi-fcs-gx
  - mosdepth
  - matplotlib
  - bbmap>=39.80,<40
  - pypolca>=0.5.0,<0.6
  - pytest>=7.0
  - pip
  - pip:
    - -e .
    - pytest-cov
